development: &default
  adapter: postgresql
  database: feishu_demo_development
  encoding: unicode
  pool: 5
  reaping_frequency: 10
  username:
  password:

test:
  <<: *default
  database: feishu_demo_test

production:
  <<: *default
  database: feishu_demo_production
  username: postgres
  password: postgres
